# Default values for teamcity.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
agent:
  image:
    repository: jetbrains/teamcity-agent
    tag: latest
    pullPolicy: IfNotPresent
  env: []
  nameFieldRefPath: spec.nodeName
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 800m
      memory: 968Mi
    requests:
      cpu: 600m
      memory: 968Mi

replicaCount: 1
storageClass: "yc-storage-hdd"
storageSize: 30Gi
artifactStorage:
  storageClass: "nfs-client"
  storageSize: 50Gi
  accessMode: ReadWriteMany
image:
  repository: jetbrains/teamcity-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8111

ingress:
  enabled: true
  annotations:
    "kubernetes.io/ingress.class": "argo-tunnel"
  path: /
  hosts:
    - tc.default.com

env:
  - name: TEAMCITY_SERVER_MEM_OPTS
    value: "-Xmx968m -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 800m
    memory: 968Mi
  requests:
    cpu: 600m
    memory: 968Mi

nodeSelector: {}

tolerations: []

affinity: {}
