dependencies:
  - name: postgresql
    version: 10.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 12.8.0
    repository: https://charts.bitnami.com/bitnami
