apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weblate.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "weblate.name" . }}
    helm.sh/chart: {{ include "weblate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "weblate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "weblate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: weblate-data
          persistentVolumeClaim:
            claimName: {{ default (include "weblate.fullname" .) }}-data
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name:  weblate-data
              mountPath: /app/data
          env:
          {{- with .Values.debug }}
            - name: WEBLATE_DEBUG
              value: "{{ if . }}1{{ else }}0{{- end }}"
          {{- end }}
          {{- with .Values.loglevel }}
            - name: WEBLATE_LOGLEVEL
              value: {{ . }}
          {{- end }}
          {{- with .Values.site_title }}
            - name: WEBLATE_SITE_TITLE
              value: {{ . }}
          {{- end }}
          {{- with .Values.admin_name }}
            - name: WEBLATE_ADMIN_NAME
              value: {{ . }}
          {{- end }}
          {{- with .Values.admin_email }}
            - name: WEBLATE_ADMIN_EMAIL
              value: {{ . }}
          {{- end }}
          {{- with .Values.admin_password }}
            - name: WEBLATE_ADMIN_PASSWORD
              value: {{ . }}
          {{- end }}
          {{- with .Values.server_email }}
            - name: WEBLATE_SERVER_EMAIL
              value: {{ . }}
          {{- end }}
          {{- with .Values.default_from_email }}
            - name: WEBLATE_DEFAULT_FROM_EMAIL
              value: {{ . }}
          {{- end }}
          {{- with .Values.allowed_hosts }}
            - name: WEBLATE_ALLOWED_HOSTS
              value: {{ . | quote }}
          {{- end }}
          {{- with .Values.registration_open }}
            - name: WEBLATE_REGISTRATION_OPEN
              value: "{{ if . }}1{{ else }}0{{- end }}"
          {{- end }}
          {{- with .Values.time_zone }}
            - name: WEBLATE_TIME_ZONE
              value: {{ . }}
          {{- end }}
          {{- with .Values.mt_google_key }}
            - name: WEBLATE_MT_GOOGLE_KEY
              value: {{ . }}
          {{- end }}
          {{- with .Values.sa }}
          {{- with .github }}
            - name: WEBLATE_SOCIAL_AUTH_GITHUB_KEY
              value: {{ .key }}
            - name: WEBLATE_SOCIAL_AUTH_GITHUB_SECRET
              value: {{ .secret }}
          {{- end }}
          {{- with .bitbucket }}
            - name: WEBLATE_SOCIAL_AUTH_BITBUCKET_KEY
              value: {{ .key }}
            - name: WEBLATE_SOCIAL_AUTH_BITBUCKET_SECRET
              value: {{ .secret }}
          {{- end }}
          {{- with .facebook }}
            - name: WEBLATE_SOCIAL_AUTH_FACEBOOK_KEY
              value: {{ .key }}
            - name: WEBLATE_SOCIAL_AUTH_FACEBOOK_SECRET
              value: {{ .secret }}
          {{- end }}
          {{- with .google }}
            - name: WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
              value: {{ .key }}
            - name: WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
              value: {{ .secret }}
          {{- end }}
          {{- end }}
          {{- with .Values.offload_indexing }}
            - name: WEBLATE_OFFLOAD_INDEXING
              value: "{{ if . }}1{{ else }}0{{- end }}"
          {{- end }}
          {{- with .Values.ga_id }}
            - name: WEBLATE_GOOGLE_ANALYTICS_ID
              value: {{ . }}
          {{- end }}
          {{- with .Values.https }}
            - name: WEBLATE_ENABLE_HTTPS
              value: "{{ if . }}1{{ else }}0{{- end }}"
          {{- end }}
          {{- with .Values.https_proxy_header }}
            - name: WEBLATE_IP_PROXY_HEADER
              value: {{ . }}
          {{- end }}
          {{- with .Values.require_login }}
            - name: WEBLATE_REQUIRE_LOGIN
              value: "{{ if . }}1{{ else }}0{{- end }}"
          {{- end }}
          {{- with .Values.ldap }}
            - name: WEBLATE_AUTH_LDAP_SERVER_URI
              value: {{ .server_uri }}
            - name: WEBLATE_AUTH_LDAP_USER_DN_TEMPLATE
              value: {{ .user_dn_template }}
            - name: WEBLATE_AUTH_LDAP_USER_ATTR_MAP
              value: {{ .user_attr_map }}
          {{- end }}
          {{- with .Values.email }}
            - name: WEBLATE_EMAIL_HOST
              value: {{ .host }}
            - name: WEBLATE_EMAIL_USER
              value: {{ .user }}
            - name: WEBLATE_EMAIL_PASSWORD
              value: {{ .password }}
          {{- end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.postgresql.existingSecret }}
                  name: {{ .Values.postgresql.existingSecret }}
                {{- else }}
                  name: {{ template "weblate.postgresql.secret" . }}
                {{- end }}
                  key: postgresql-password
            - name: POSTGRES_USER
              value: {{ default "weblate" .Values.postgresql.postgresUser | quote }}
            - name: POSTGRES_DATABASE
              value: {{ default "weblate" .Values.postgresql.postgresDatabase | quote }}
            - name: POSTGRES_HOST
              value: {{ template "weblate.postgresql.host" . }}
            - name: POSTGRES_PORT
              value: {{ template "weblate.postgresql.port" . }}
            - name: REDIS_HOST
              value: {{ template "weblate.redis.fullname" . }}-master
            - name: REDIS_PORT
              value: {{ template "weblate.redis.port" . }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
