apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager-bot.fullname" . }}
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
data:
{{- range $name, $value := .Values.templates }}
  {{ $name }}: |
    {{- $value | nindent 4 }}
{{- end }}
