apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-bot.fullname" . }}
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
data:
  admin: {{ .Values.telegram.admin | b64enc | quote }}
  token: {{ .Values.telegram.token | b64enc | quote }}
