{{- $fullName := default (include "teamcity.fullname" .) -}}
{{- with .Values.dataStorage }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-data
spec:
  storageClassName: {{ .storageClass }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .storageSize }}
{{- end }}
