{{- $fullName := default (include "teamcity.fullname" .) -}}
{{- with .Values.logsStorage }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-logs
spec:
  storageClassName: {{ .storageClass }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .storageSize }}
{{- end}}
