{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "teamcity.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "teamcity.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "teamcity.serviceAccountName" . }}
{{- end -}}
