apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "teamcity.fullname" . }}
  labels:
    app: {{ template "teamcity.name" . }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "teamcity.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "teamcity.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: server-data
          persistentVolumeClaim:
            claimName: {{ default (include "teamcity.fullname" .) }}-server-data
        - name: artifacts
          persistentVolumeClaim:
            claimName: {{ default (include "teamcity.fullname" .) }}-artifacts
        - name: logs
          persistentVolumeClaim:
            claimName: {{ default (include "teamcity.fullname" .) }}-logs
        - name: temp
          emptyDir: {}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: logs
              mountPath: /opt/teamcity/logs
            - name: temp
              mountPath: /opt/teamcity/temp
            - name:  server-data
              mountPath: /data/teamcity_server/datadir
            - name: artifacts
              mountPath: /data/teamcity_server/datadir/system/artifacts
          ports:
            - name: http
              containerPort: 8111
              protocol: TCP
        {{- with .Values.env }}
          env:
{{ toYaml . | indent 12 }}
        {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
